python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/5.jpg -i images/inputs/4.png -o images/outputs/tmpl_5_inp_4.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/3.jpg -i images/inputs/4.png -o images/outputs/tmpl_3_inp_4.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/2.jpg -i images/inputs/4.png -o images/outputs/tmpl_2_inp_4.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/1.png -i images/inputs/4.png -o images/outputs/tmpl_1_inp_4.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/4.jpg -i images/inputs/4.png -o images/outputs/tmpl_4_inp_4.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/5.jpg -i images/inputs/5.jpg -o images/outputs/tmpl_5_inp_5.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/3.jpg -i images/inputs/5.jpg -o images/outputs/tmpl_3_inp_5.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/2.jpg -i images/inputs/5.jpg -o images/outputs/tmpl_2_inp_5.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/1.png -i images/inputs/5.jpg -o images/outputs/tmpl_1_inp_5.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/4.jpg -i images/inputs/5.jpg -o images/outputs/tmpl_4_inp_5.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/5.jpg -i images/inputs/6.jpg -o images/outputs/tmpl_5_inp_6.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/3.jpg -i images/inputs/6.jpg -o images/outputs/tmpl_3_inp_6.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/2.jpg -i images/inputs/6.jpg -o images/outputs/tmpl_2_inp_6.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/1.png -i images/inputs/6.jpg -o images/outputs/tmpl_1_inp_6.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/4.jpg -i images/inputs/6.jpg -o images/outputs/tmpl_4_inp_6.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/5.jpg -i images/inputs/2.jpg -o images/outputs/tmpl_5_inp_2.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/3.jpg -i images/inputs/2.jpg -o images/outputs/tmpl_3_inp_2.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/2.jpg -i images/inputs/2.jpg -o images/outputs/tmpl_2_inp_2.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/1.png -i images/inputs/2.jpg -o images/outputs/tmpl_1_inp_2.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/4.jpg -i images/inputs/2.jpg -o images/outputs/tmpl_4_inp_2.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/5.jpg -i images/inputs/3.png -o images/outputs/tmpl_5_inp_3.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/3.jpg -i images/inputs/3.png -o images/outputs/tmpl_3_inp_3.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/2.jpg -i images/inputs/3.png -o images/outputs/tmpl_2_inp_3.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/1.png -i images/inputs/3.png -o images/outputs/tmpl_1_inp_3.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/4.jpg -i images/inputs/3.png -o images/outputs/tmpl_4_inp_3.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/5.jpg -i images/inputs/1.jpg -o images/outputs/tmpl_5_inp_1.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/3.jpg -i images/inputs/1.jpg -o images/outputs/tmpl_3_inp_1.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/2.jpg -i images/inputs/1.jpg -o images/outputs/tmpl_2_inp_1.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/1.png -i images/inputs/1.jpg -o images/outputs/tmpl_1_inp_1.png
python main.py -p res/shape_predictor_68_face_landmarks.dat -t images/templates/4.jpg -i images/inputs/1.jpg -o images/outputs/tmpl_4_inp_1.png
